/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevelacaoRouteImport } from './routes/revelacao'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as IndexRouteImport } from './routes/index'

const RevelacaoRoute = RevelacaoRouteImport.update({
  id: '/revelacao',
  path: '/revelacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produtos': typeof ProdutosRoute
  '/revelacao': typeof RevelacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produtos': typeof ProdutosRoute
  '/revelacao': typeof RevelacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/produtos': typeof ProdutosRoute
  '/revelacao': typeof RevelacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/produtos' | '/revelacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/produtos' | '/revelacao'
  id: '__root__' | '/' | '/produtos' | '/revelacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdutosRoute: typeof ProdutosRoute
  RevelacaoRoute: typeof RevelacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revelacao': {
      id: '/revelacao'
      path: '/revelacao'
      fullPath: '/revelacao'
      preLoaderRoute: typeof RevelacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdutosRoute: ProdutosRoute,
  RevelacaoRoute: RevelacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
